version: '3'
services:
  frontend_server:
    image: sujeong7474/react-crashingdev:latest
    restart: "on-failure"
    ports:
      - 80:80
    networks:
      - portfolio-service
  backend_server:
    image: sujeong7474/node-crashingdev:latest
    restart: "on-failure"
    ports:
      - 5005:5005
    networks:
      - portfolio-service
  data_server:
    image: sujeong7474/flask-crashingdev:latest
    restart: "on-failure"
    ports:
      - 8000:8000
    networks:
      - portfolio-service
